#cloud-config
hostname: ${role}-aws
manage_etc_hosts: true

users:
  - name: adminuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${ssh_key}

package_update: true
package_upgrade: true
packages:
  - curl
  - unzip
