cloud_provider: aws
ssh_key:
  azure: ~/.ssh/id_rsa.pub
  hetzner: hetzner_key
  aws: id_rsa_aws
ssh_key_path:
  azure: /home/adminuser/.ssh/id_rsa
  hetzner: /home/adminuser/.ssh/id_ed25519
  aws: /home/adminuser/.ssh/id_rsa_aws

region:
  azure: westeurope
  hetzner: fsn1
  aws: eu-central-1

instance_type:
  azure:
    management: Standard_B1ms
    k8s_master: Standard_B2s
    k8s_worker: Standard_B2s
    storage: Standard_B2s
    monitoring: Standard_B1s
  hetzner:
    management: cpx21
    k8s_master: cpx31
    k8s_worker: cpx31
    storage: cpx31
    monitoring: cpx21
  aws:
    management: t2.micro
    k8s_master: t2.medium
    k8s_worker: t2.medium
    storage: t2.micro
    monitoring: t2.micro

vm_count:
  azure:
    management: 1
    k8s_master: 1
    k8s_worker: 1
    storage: 1
    monitoring: 1
  hetzner:
    management: 1
    k8s_master: 1
    k8s_worker: 1
    storage: 1
    monitoring: 1
  aws:
    management: 1
    k8s_master: 1
    k8s_worker: 1
    storage: 1
    monitoring: 1

extra_disks:
  azure:
    - name: disk1
      size: 20
      type: Standard_LRS
    - name: disk2
      size: 20
      type: Standard_LRS
  hetzner:
    - name: disk1
      size: 20
      type: hdd
    - name: disk2
      size: 20
      type: hdd
  aws:
    - name: disk1
      size: 20
      type: gp2
    - name: disk2
      size: 20
      type: gp2
