- name: Configure k8s-master
  hosts: k8s_masters
  become: yes
  tasks:

    - name: Pull images
      ansible.builtin.command:
        cmd: sudo kubeadm config images pull --cri-socket unix:///var/run/containerd/containerd.sock

    - name: Initialize control-plane
      ansible.builtin.command:
        cmd: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket unix:///var/run/containerd/containerd.sock --v=5

    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/adminuser/.kube/config
        remote_src: yes
        owner: "adminuser"
        group: "adminuser"
        mode: '0600'

    - name: Add network add-on
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      become: no

    - name: Fetch Kubernetes config from master
      ansible.builtin.fetch:
        src: /home/adminuser/.kube/config
        dest: ./files/kube_config
        flat: yes
      delegate_to: "{{ groups['k8s_masters'][0] }}"
      run_once: yes

    - name: Copy k8s config to worker
      ansible.builtin.copy:
        src: ./files/kube_config
        dest: /home/adminuser/.kube/config
        owner: adminuser
        group: adminuser
        mode: '0644'
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k8s_workers'] }}"

    - name: Get kubeadm join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command

    - name: Join Worker Nodes to cluster
      ansible.builtin.shell: "{{ join_command.stdout }}"
      args:
        executable: /bin/bash
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k8s_workers'] }}"

    - name: Labeling worker-node
      ansible.builtin.command:
        cmd: kubectl label node {{ item }} node-role.kubernetes.io/worker=
      loop: "{{ groups['k8s_workers'] }}"
      become: no

    - name: Add Helm APT Repo
      ansible.builtin.shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install helm
      ansible.builtin.apt:
        name:
          - helm
        state: present